spring.application.name=calm_breath
spring.datasource.url=jdbc:postgresql://localhost:5432/calm_breath
spring.datasource.username=calm_breath_user
spring.datasource.password=calm_breath_pass
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml